org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=knockoutmod
mod_name=Still-Breathing
mod_license=MIT
mod_version=1.4.7
epicfight_version=20.13.6-1.20.1
mod_group_id=com.knockoutmod
mod_authors=krendel001
mod_description=Turn lethal damage into a downed state instead of instant death. Hold sneak to struggle back up, allies can revive you, enemies can finish you off, and survivors can loot your gear before you bleed out. Fully configurable for hardcore squads and PvP.
mod_github=https://github.com/krendel001/Still-Breathing
mod_issues=https://github.com/krendel001/Still-Breathing/issues
mod_homepage=https://modrinth.com/mod/still-breathing
